import ExcelJS from "exceljs";
import PDFDocument from "pdfkit";
import { getKpiDefinition } from "../semantic/kpiDictionary.js";
import type { AppUser } from "../rbac/users.js";
import { roleLabel } from "../rbac/roleLabel.js";
import type { ReportResult } from "./execute.js";

/**
 * Report stamping + export (spec §49). Every exported file carries company,
 * report name, generated user, role, date/time, report ID, data-as-of, and
 * filters, so a shared PDF/Excel is self-describing without the app.
 */
const COMPANY_NAME = "Retail Intelligence Platform (demo)";

function formatValue(id: string, v: number): string {
  const unit = getKpiDefinition(id)?.unit ?? "count";
  if (unit === "SAR") return `SAR ${Math.round(v).toLocaleString()}`;
  if (unit === "percent") return `${(v * 100).toFixed(1)}%`;
  if (unit === "days") return v.toFixed(0);
  return v.toLocaleString();
}

function kpiLabel(id: string): string {
  return getKpiDefinition(id)?.nameEn ?? id;
}

function stampLines(result: ReportResult, user: AppUser): string[] {
  return [
    `${COMPANY_NAME}`,
    `Report: ${result.definition.name || "Ad-hoc report"}`,
    `Generated by: ${user.name} (${roleLabel(user.role)})`,
    `Generated at: ${new Date().toISOString()}`,
    `Report ID: ${result.definition.id}`,
    `Data as of: ${result.dataAsOf}`,
    `Period: ${result.definition.dateFrom} to ${result.definition.dateTo}`,
    `Confidence: ${result.confidence.toUpperCase()} — ${result.confidenceReason}`,
  ];
}

export async function exportReportToExcel(result: ReportResult, user: AppUser): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = user.name;
  workbook.created = new Date();

  const sheet = workbook.addWorksheet("Report");
  const stamp = stampLines(result, user);
  stamp.forEach((line) => sheet.addRow([line]));
  sheet.addRow([]);

  const dimHeader = result.definition.dimensions[0] ?? "Dimension";
  const headerRow = sheet.addRow([dimHeader, ...result.definition.metrics.map(kpiLabel)]);
  headerRow.font = { bold: true };

  for (const row of result.rows) {
    sheet.addRow([row.dimensionLabel, ...result.definition.metrics.map((m) => formatValue(m, row.metrics[m] ?? 0))]);
  }

  sheet.addRow([]);
  sheet.addRow(["Total", ...result.definition.metrics.map((m) => formatValue(m, result.totals[m] ?? 0))]).font = { bold: true };

  sheet.columns.forEach((col) => {
    col.width = 22;
  });

  const buffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(buffer);
}

export function exportReportToPdf(result: ReportResult, user: AppUser): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 40, size: "A4" });
    const chunks: Buffer[] = [];
    doc.on("data", (c) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fontSize(14).text(result.definition.name || "Ad-hoc report", { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(9).fillColor("#555");
    for (const line of stampLines(result, user).slice(1)) {
      doc.text(line);
    }
    doc.fillColor("#000");
    doc.moveDown(1);

    const dimHeader = result.definition.dimensions[0] ?? "Dimension";
    const columns = [dimHeader, ...result.definition.metrics.map(kpiLabel)];
    const colWidth = (doc.page.width - 80) / columns.length;

    doc.fontSize(10).font("Helvetica-Bold");
    columns.forEach((c, i) => doc.text(c, 40 + i * colWidth, doc.y, { width: colWidth, continued: i < columns.length - 1 }));
    doc.moveDown(0.5);
    doc.font("Helvetica");

    for (const row of result.rows) {
      const y = doc.y;
      const cells = [row.dimensionLabel, ...result.definition.metrics.map((m) => formatValue(m, row.metrics[m] ?? 0))];
      cells.forEach((c, i) => doc.text(c, 40 + i * colWidth, y, { width: colWidth }));
      doc.moveDown(0.3);
    }

    doc.moveDown(0.5);
    doc.font("Helvetica-Bold");
    const totalY = doc.y;
    ["Total", ...result.definition.metrics.map((m) => formatValue(m, result.totals[m] ?? 0))].forEach((c, i) =>
      doc.text(c, 40 + i * colWidth, totalY, { width: colWidth }),
    );

    doc.end();
  });
}
